# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facetrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=255, verbose_name='序列id')),
                ('age', models.IntegerField(db_index=True, default=0, verbose_name='年龄')),
                ('createdate', models.DateTimeField(db_index=True, verbose_name='创建日期')),
                ('descriptor', models.CharField(max_length=255, verbose_name='采集信息')),
                ('glasses', models.IntegerField(verbose_name='眼镜')),
                ('sex', models.IntegerField(db_index=True, verbose_name='性别')),
                ('src_id', models.CharField(max_length=255, verbose_name='视频源id')),
                ('state', models.IntegerField()),
                ('score', models.FloatField(db_index=True, default=0, verbose_name='相似度')),
                ('status', models.IntegerField(db_index=True, verbose_name='处理状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'facetrack',
            },
        ),
        migrations.CreateModel(
            name='Facetrack_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='图片名称')),
                ('quality', models.FloatField(verbose_name='图片质量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('facetrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Facetrack')),
            ],
            options={
                'db_table': 'facetrack_images',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=255, verbose_name='人物id')),
                ('name', models.CharField(db_index=True, default='', max_length=255, verbose_name='姓名')),
                ('age', models.IntegerField(db_index=True, default=0, verbose_name='年龄')),
                ('sex', models.IntegerField(db_index=True, default=-1, verbose_name='性别')),
                ('card_id', models.CharField(db_index=True, default='', max_length=255, verbose_name='身份证号')),
                ('job', models.CharField(db_index=True, default='', max_length=255, verbose_name='工作')),
                ('job_id', models.CharField(db_index=True, default='', max_length=255, verbose_name='工号')),
                ('address', models.CharField(db_index=True, default='', max_length=255, verbose_name='住址')),
                ('remark', models.CharField(default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Person_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='分组名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'person_group',
            },
        ),
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_key', models.CharField(max_length=255, verbose_name='应用key')),
                ('match_threshold', models.FloatField(verbose_name='匹配阈值')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Person_Group'),
        ),
        migrations.AddField(
            model_name='facetrack',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Person'),
        ),
    ]
