# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180103_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetrack',
            name='is_added',
            field=models.IntegerField(db_index=True, default=0, verbose_name='是否添加至person'),
        ),
    ]
