# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_facetrack_is_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True, verbose_name='生日'),
        ),
    ]
