# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nick_name',
            field=models.CharField(default='', max_length=255, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='facetrack',
            name='is_added',
            field=models.BooleanField(db_index=True, default=0, verbose_name='是否添加至person'),
        ),
    ]
