# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_person_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='facetrack',
            name='status_card',
            field=models.IntegerField(db_index=True, default=0, verbose_name='身份证读取状态'),
        ),
        migrations.AddField(
            model_name='person',
            name='card_agency',
            field=models.CharField(default='', max_length=255, verbose_name='身份证签发机关'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default='', max_length=255, verbose_name='民族'),
        ),
    ]
