# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20180117_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='card_startdate',
            field=models.DateField(null=True, verbose_name='身份证签发日期'),
        ),
    ]
