# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_person_card_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facetrack',
            name='status_card',
        ),
    ]
